apiVersion: v1
kind: Service
metadata:
  name: prime-lb
spec:
  ports:
  - port: 80
    targetPort: http-port
    protocol: TCP
  selector:
    app: prime-web
  type: LoadBalancer
  sessionAffinity: ClientIP
